// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zesdzauddkcjiaurtfgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplc2R6YXVkZGtjamlhdXJ0ZmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDg1ODIsImV4cCI6MjA2OTI4NDU4Mn0.veyRc0KRVfwsl2_V6M35gNXGj9gvZfRNU-w2Rp4mE8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});